name: Pi Project
id: pi-project
created: 2026-09-13T15:59:00.845Z
updated: 2026-09-14T15:29:27.972Z
repositories:
  - ~/Projects/pi-project-management
resources: []
workspace: ~/Projects
yolo: false
auto_commit: true
active_plan: P2
completed: false
completed_at: null
paused: false
paused_at: null
resume_note: null
